# Generated by Django 4.0.5 on 2022-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('author', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
