# Generated by Django 4.0.5 on 2022-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('tb', 'Текстовый блог'), ('mb', 'Музыкальный блог')], default='tb', max_length=50),
        ),
    ]
